
"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-loj#=y-)%7($skkdo-q4s6$l6gs+%9%5n*19z=3j8gy95oujaj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]

# ==========================================
# FIXED STATIC FILES (No more 'os' error!)
# ==========================================
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles' # Required for production deployment

# Application definition
INSTALLED_APPS = [
    'myapp.apps.MyappConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'recruitment',
    'documents',
    'ai_engine',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

AUTH_USER_MODEL = 'accounts.User'
# """
# Django settings for config project.
#
# Generated by 'django-admin startproject' using Django 6.0.4.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """
#
# from pathlib import Path
#
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
#
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-loj#=y-)%7($skkdo-q4s6$l6gs+%9%5n*19z=3j8gy95oujaj'
#
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
#
# ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
#
#
# # Application definition
#
# INSTALLED_APPS = [
#     'myapp.apps.MyappConfig',
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'accounts',
#     'recruitment',
#     'documents',
#     'ai_engine',
#     'rest_framework',
# ]
#
# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]
# # CRONJOBS = [
# #     ('*/2 * * * *', 'myapp.cron.run_daily_etl'),
# # ]
#
# ROOT_URLCONF = 'config.urls'
#
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = 'config.wsgi.application'
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media'
#
# # Database
# # https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
#
#
# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]
#
#
# # Internationalization
# # https://docs.djangoproject.com/en/6.0/topics/i18n/
#
# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_TZ = True
# AUTH_USER_MODEL = 'accounts.User'
#
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/
#
# STATIC_URL = 'static/'

# # Base Python image set exactly to your local version
# FROM python:3.13-slim

# # Prevent Python from writing .pyc files
# ENV PYTHONDONTWRITEBYTECODE=1
# ENV PYTHONUNBUFFERED=1

# # Set work directory
# WORKDIR /app

# # =========================
# # SYSTEM DEPENDENCIES (With Rust & Cargo for Python 3.13)
# # =========================
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     curl \
#     wget \
#     unzip \
#     gnupg2 \
#     ca-certificates \
#     apt-transport-https \
#     gcc \
#     g++ \
#     unixodbc \
#     unixodbc-dev \
#     curl \
#     # We add these two explicitly so Python 3.13 can compile python-bidi and other source files
#     cargo \
#     rustc \
#     && rm -rf /var/lib/apt/lists/*

# # =========================
# # MICROSOFT ODBC DRIVER
# # =========================
# RUN mkdir -p /etc/apt/keyrings

# RUN curl -sSL https://packages.microsoft.com/keys/microsoft.asc \
#     | gpg --dearmor > /etc/apt/keyrings/microsoft.gpg

# RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/debian/12/prod bookworm main" \
#     > /etc/apt/sources.list.d/mssql-release.list

# RUN apt-get update && ACCEPT_EULA=Y apt-get install -y --no-install-recommends msodbcsql18 \
#     && rm -rf /var/lib/apt/lists/*

# # =========================
# # DOWNLOAD ML MODELS
# # =========================
# RUN mkdir -p /app/ml_models

# # Install gdown to bypass Google Drive's virus scan confirmation page safely
# RUN pip install --no-cache-dir gdown

# # Download using gdown via the file ID directly
# RUN gdown 1vXtOXOE7MHF2BGvNYpNBAz8oz5zf3gBJ -O /tmp/models.zip

# # Unzip into ml_models directory
# RUN unzip /tmp/models.zip -d /app/ml_models && \
#     rm /tmp/models.zip

# # =========================
# # PYTHON DEPENDENCIES
# # =========================
# COPY requirements.txt .

# # Upgrade pip and install all requirements cleanly
# RUN pip install --upgrade pip && \
#     pip install --no-cache-dir -r requirements.txt

# # Explicitly install the ultra-lightweight CPU version of Torch inside the container image
# RUN pip install torch==2.11.0 --index-url https://download.pytorch.org/whl/cpu --no-cache-dir

# # =========================
# # PROJECT FILES
# # =========================
# COPY . .

# # =========================
# # EXPOSE PORT
# # =========================
# EXPOSE 8000

# # =========================
# # START COMMAND (Production Ready Gunicorn)
# # =========================
# CMD ["gunicorn", "--bind=0.0.0.0:8000", "--pythonpath", "/app", "config.wsgi:application"]
# # # Base Python image
# # FROM python:3.13-slim

# # # Prevent Python from writing .pyc files
# # ENV PYTHONDONTWRITEBYTECODE=1
# # ENV PYTHONUNBUFFERED=1

# # # Set work directory
# # WORKDIR /app

# # # =========================
# # # SYSTEM DEPENDENCIES
# # # =========================
# # RUN apt-get update && apt-get install -y \
# #     curl \
# #     wget \
# #     unzip \
# #     gnupg2 \
# #     ca-certificates \
# #     apt-transport-https \
# #     gcc \
# #     g++ \
# #     unixodbc \
# #     unixodbc-dev \
# #     && rm -rf /var/lib/apt/lists/*

# # # =========================
# # # MICROSOFT ODBC DRIVER
# # # =========================

# # RUN mkdir -p /etc/apt/keyrings

# # RUN curl -sSL https://packages.microsoft.com/keys/microsoft.asc \
# #     | gpg --dearmor > /etc/apt/keyrings/microsoft.gpg

# # RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/debian/12/prod bookworm main" \
# #     > /etc/apt/sources.list.d/mssql-release.list

# # RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql18 \
# #     && rm -rf /var/lib/apt/lists/*

# # # =========================
# # # DOWNLOAD ML MODELS
# # # =========================

# # RUN mkdir -p /app/ml_models

# # # Download ZIP from Google Drive
# # RUN wget --no-check-certificate \
# #     "https://drive.google.com/uc?export=download&id=1vXtOXOE7MHF2BGvNYpNBAz8oz5zf3gBJ" \
# #     -O /tmp/models.zip

# # # Unzip into ml_models directory
# # RUN unzip /tmp/models.zip -d /app/ml_models && \
# #     rm /tmp/models.zip

# # # =========================
# # # PYTHON DEPENDENCIES
# # # =========================
# # COPY requirements.txt .

# # RUN pip install --upgrade pip && \
# #     pip install -r requirements.txt

# # # =========================
# # # PROJECT FILES
# # # =========================
# # COPY . .

# # # =========================
# # # EXPOSE PORT
# # # =========================
# # EXPOSE 8000

# # # =========================
# # # START COMMAND
# # # =========================
# # CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
# # # # Base Python image
# # # FROM python:3.13-slim

# # # # Prevent Python from writing .pyc files
# # # ENV PYTHONDONTWRITEBYTECODE=1
# # # ENV PYTHONUNBUFFERED=1

# # # # Set work directory
# # # WORKDIR /app

# # # # =========================
# # # # SYSTEM DEPENDENCIES
# # # # =========================
# # # RUN apt-get update && apt-get install -y \
# # #     curl \
# # #     gnupg2 \
# # #     ca-certificates \
# # #     apt-transport-https \
# # #     gcc \
# # #     g++ \
# # #     unixodbc \
# # #     unixodbc-dev \
# # #     && rm -rf /var/lib/apt/lists/*

# # # # =========================
# # # # MICROSOFT ODBC DRIVER (FIXED MODERN WAY)
# # # # =========================

# # # RUN mkdir -p /etc/apt/keyrings

# # # RUN curl -sSL https://packages.microsoft.com/keys/microsoft.asc \
# # #     | gpg --dearmor > /etc/apt/keyrings/microsoft.gpg

# # # RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/debian/12/prod bookworm main" \
# # #     > /etc/apt/sources.list.d/mssql-release.list

# # # RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql18 \
# # #     && rm -rf /var/lib/apt/lists/*

# # # # =========================
# # # # PYTHON DEPENDENCIES
# # # # =========================
# # # COPY requirements.txt .

# # # RUN pip install --upgrade pip && \
# # #     pip install -r requirements.txt

# # # # =========================
# # # # PROJECT FILES
# # # # =========================
# # # COPY . .

# # # # =========================
# # # # EXPOSE PORT
# # # # =========================
# # # EXPOSE 8000

# # # # =========================
# # # # START COMMAND
# # # # =========================
# # # CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
