# Generated by Django 6.0.4 on 2026-05-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='quiz_score',
            field=models.FloatField(default=0),
        ),
    ]
