# Generated by Django 6.0.4 on 2026-05-08 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recruitmentpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_post', models.DateTimeField(auto_now_add=True)),
                ('situation', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=20)),
                ('imported', models.BooleanField(default=False)),
                ('cv_file', models.TextField()),
                ('extracted_cv_content', models.TextField(blank=True, null=True)),
                ('motivation_letter', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='accounts.candidateprofile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='accounts.recruitmentpost')),
            ],
            options={
                'unique_together': {('candidate', 'post')},
            },
        ),
    ]
