# Generated by Django 6.0.4 on 2026-05-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidature_quiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='is_hired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidature',
            name='proposed_salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
