# Generated by Django 5.2.14 on 2026-05-15 14:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_recruitmentpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="cvs/"),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="education",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="experience",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="motivation_letter",
            field=models.FileField(
                blank=True, null=True, upload_to="motivation_letters/"
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="skills",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="domains",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="expertise",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="number_of_employees",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recruitmentpost",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Candidature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_post", models.DateTimeField(auto_now_add=True)),
                (
                    "situation",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("imported", models.BooleanField(default=False)),
                ("cv_file", models.FileField(upload_to="candidatures/cvs/")),
                (
                    "motivation_letter_file",
                    models.FileField(
                        blank=True, null=True, upload_to="candidatures/letters/"
                    ),
                ),
                ("extracted_cv_content", models.TextField(blank=True, null=True)),
                ("motivation_letter", models.TextField(blank=True, null=True)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("cover_message", models.TextField(blank=True)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="accounts.candidateprofile",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidatures",
                        to="accounts.recruitmentpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_of_post"],
                "unique_together": {("candidate", "post")},
            },
        ),
        migrations.CreateModel(
            name="RejectedCandidature",
            fields=[
                (
                    "ref",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                (
                    "date_of_post",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("cv_file", models.FileField(upload_to="candidatures_rejected/cvs/")),
                (
                    "motivation_letter_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="candidatures_rejected/letters/",
                    ),
                ),
                ("extracted_cv_content", models.TextField(blank=True, null=True)),
                ("motivation_letter", models.TextField(blank=True, null=True)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("cover_message", models.TextField(blank=True)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "rejected_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejected_candidatures",
                        to="accounts.candidateprofile",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejected_candidatures",
                        to="accounts.recruitmentpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-rejected_at"],
                "unique_together": {("candidate", "post")},
            },
        ),
    ]
