# Generated by Django 6.0.4 on 2026-05-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_candidateprofile_id_alter_candidature_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='ai_last_analysis_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='ai_recommendation',
            field=models.CharField(blank=True, choices=[('recommend_accept', 'À accepter'), ('borderline', 'À examiner'), ('recommend_reject', 'À refuser')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='ai_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rejectedcandidature',
            name='ai_last_analysis_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rejectedcandidature',
            name='ai_recommendation',
            field=models.CharField(blank=True, choices=[('recommend_accept', 'À accepter'), ('borderline', 'À examiner'), ('recommend_reject', 'À refuser')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='rejectedcandidature',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rejectedcandidature',
            name='ai_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rejectedcandidature',
            name='auto_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
